web:
    image: tp33/django
    external_links:
      -  mysql:db
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: bash -c "python /app/manage.py makemigrations && python /app/manage.py migrate && mod_wsgi-express start-server --working-directory /app/ --reload-on-changes /app/vote/wsgi.py"