<<<<<<< HEAD
mysql:
    image: mysql:5.7.14
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=meme12345
      - MYSQL_DATABASE=cs3240
      - MYSQL_USER=electionadmin
      - MYSQL_PASSWORD=meme12345
    volumes:
      - ./db:/var/lib/mysql

=======
>>>>>>> 79ea98fc936d22bd02128d6fad2de26aaf2ef202
web:
    image: tp33/django
    external_links:
      -  mysql:db
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: bash -c "python /app/manage.py makemigrations && python /app/manage.py migrate && mod_wsgi-express start-server --working-directory /app/ --reload-on-changes /app/vote/wsgi.py"
