# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-08 21:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20180408_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='password',
        ),
    ]
