# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-10 23:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20180408_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='photo_id',
        ),
    ]
