# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-08 21:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='date_of_birth',
            field=models.DateField(default=datetime.date.today, max_length=8),
        ),
        migrations.AddField(
            model_name='voter',
            name='election_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='voter',
            name='locality',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='voter',
            name='photo_id',
            field=models.CharField(default='', max_length=20),
        ),
    ]
